import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { RewardService } from '../../core/services/reward.service';

@Component({
  selector: 'app-rewards',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div class="space-y-8 text-text-main pb-10">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div class="flex items-center gap-3">
            <h1 class="text-3xl font-extrabold tracking-tight text-text-main">Rewards & Cashback</h1>
            <span *ngIf="isDemoMode" class="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-brand-primary-light text-brand-primary-dark border border-brand-primary/30">
              Demo Values Active
            </span>
          </div>
          <p class="text-text-sub text-sm mt-1">Track reward points and real cashbacks generated by your transactions.</p>
        </div>

        <!-- Controls: Demo Toggle & Guide Pills -->
        <div class="flex flex-wrap items-center gap-2">
          <button 
            (click)="toggleGuide()" 
            class="text-xs font-semibold px-3.5 py-2 rounded-2xl border transition-all duration-200 flex items-center gap-1.5 shadow-sm"
            [ngClass]="showGuide ? 'bg-brand-primary text-white border-brand-primary' : 'bg-white text-text-sub border-brand-border hover:bg-brand-bg'"
          >
            <span>💡</span>
            <span>{{ showGuide ? 'Hide Guide' : 'What is Where?' }}</span>
          </button>

          <div class="flex items-center bg-white border border-brand-border rounded-2xl p-1 shadow-sm">
            <button 
              (click)="setMode(true)" 
              class="text-xs font-semibold px-3 py-1.5 rounded-xl transition-all duration-150"
              [ngClass]="isDemoMode ? 'bg-brand-primary-light text-brand-primary-dark font-bold' : 'text-text-sub hover:text-text-main'"
            >
              Sample Data
            </button>
            <button 
              (click)="setMode(false)" 
              class="text-xs font-semibold px-3 py-1.5 rounded-xl transition-all duration-150"
              [ngClass]="!isDemoMode ? 'bg-brand-primary-light text-brand-primary-dark font-bold' : 'text-text-sub hover:text-text-main'"
            >
              Live Data
            </button>
          </div>

          <button 
            (click)="openAddModal()" 
            class="px-4 py-2.5 bg-brand-primary hover:bg-brand-primary-dark text-white text-xs font-bold rounded-2xl shadow-sm hover:shadow transition-all duration-200 focus:outline-none flex items-center gap-2"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
            </svg>
            Record Reward
          </button>
        </div>
      </div>

      <!-- Cashback Summary Cards -->
      <div *ngIf="!loading" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div class="bg-brand-primary-light border border-brand-primary p-5 rounded-2xl shadow-sm">
          <div *ngIf="showGuide" class="text-[10px] font-bold text-brand-primary-dark bg-white px-2 py-0.5 rounded-md mb-2 w-fit">
            📍 Total Inflow Cashback
          </div>
          <span class="text-[10px] font-bold text-brand-primary-dark uppercase tracking-wider">Total Cashback</span>
          <h3 class="text-2xl font-black text-brand-primary-dark mt-1">₹{{ totalCashback | number:'1.2-2' }}</h3>
        </div>

        <div class="bg-white border border-brand-border p-5 rounded-2xl shadow-sm">
          <div *ngIf="showGuide" class="text-[10px] font-bold text-emerald-800 bg-emerald-100 px-2 py-0.5 rounded-md mb-2 w-fit">
            📍 Deposited to Account
          </div>
          <span class="text-[10px] font-bold text-text-sub uppercase tracking-wider">Credited Cash</span>
          <h3 class="text-2xl font-black text-emerald-600 mt-1">₹{{ creditedCashback | number:'1.2-2' }}</h3>
        </div>

        <div class="bg-white border border-brand-border p-5 rounded-2xl shadow-sm">
          <div *ngIf="showGuide" class="text-[10px] font-bold text-orange-800 bg-orange-100 px-2 py-0.5 rounded-md mb-2 w-fit">
            📍 Processing
          </div>
          <span class="text-[10px] font-bold text-text-sub uppercase tracking-wider">Pending Release</span>
          <h3 class="text-2xl font-black text-orange-500 mt-1">₹{{ pendingCashback | number:'1.2-2' }}</h3>
        </div>

        <div class="bg-white border border-brand-border p-5 rounded-2xl shadow-sm">
          <div *ngIf="showGuide" class="text-[10px] font-bold text-purple-800 bg-purple-100 px-2 py-0.5 rounded-md mb-2 w-fit">
            📍 Loyalty Points Balance
          </div>
          <span class="text-[10px] font-bold text-text-sub uppercase tracking-wider">Redeemed Points</span>
          <h3 class="text-2xl font-black text-purple-600 mt-1">{{ totalPoints | number:'1.0-0' }} pts</h3>
        </div>
      </div>

      <!-- State: Loading -->
      <div *ngIf="loading" class="p-12 text-center text-xs text-text-sub">
        Loading rewards details...
      </div>

      <!-- Empty state -->
      <div *ngIf="!loading && rewards.length === 0" class="bg-white border border-brand-border p-12 rounded-2xl text-center shadow-sm space-y-3">
        <p class="text-sm text-text-sub">No reward items recorded yet.</p>
        <button (click)="openAddModal()" class="text-xs text-brand-primary font-bold underline">Add a reward item</button>
      </div>

      <!-- Rewards List -->
      <div *ngIf="!loading && rewards.length > 0" class="bg-white border border-brand-border rounded-2xl shadow-sm overflow-hidden relative">
        <div *ngIf="showGuide" class="p-4 pb-0">
          <span class="inline-flex items-center gap-1 text-[10px] font-bold text-brand-primary-dark bg-brand-primary-light px-2.5 py-0.5 rounded-md">
            📍 Rewards Activity Log: Cashback incentives earned from specific purchases
          </span>
        </div>

        <div class="divide-y divide-brand-border">
          <div *ngFor="let rew of rewards" class="p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-brand-bg transition-colors duration-150">
            <div class="flex items-center gap-4">
              <div class="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 font-black flex items-center justify-center border border-amber-200 text-lg shadow-xs">
                🎁
              </div>
              <div>
                <h4 class="font-bold text-sm text-text-main">{{ rew.title || rew.rewardType?.replace('_', ' ') }}</h4>
                <p class="text-xs text-text-sub mt-0.5">
                  Earned: {{ rew.earnedDate | date:'MMM d, yyyy' }} &middot; 
                  <span class="capitalize">{{ rew.rewardType?.toLowerCase()?.replace('_', ' ') }}</span>
                </p>
              </div>
            </div>

            <div class="flex items-center justify-between sm:justify-end gap-6">
              <div class="text-right">
                <span class="font-extrabold text-sm text-emerald-700 block">+₹{{ rew.amount | number:'1.2-2' }}</span>
                <span class="px-2 py-0.5 rounded-md text-[10px] font-bold uppercase"
                      [class.bg-emerald-50]="rew.status === 'EARNED' || rew.status === 'CREDITED'"
                      [class.text-emerald-700]="rew.status === 'EARNED' || rew.status === 'CREDITED'"
                      [class.bg-orange-50]="rew.status === 'PENDING'"
                      [class.text-orange-700]="rew.status === 'PENDING'">
                  {{ rew.status }}
                </span>
              </div>
              <button (click)="deleteReward(rew.rewardId)" class="text-xs text-red-500 hover:text-red-700 font-semibold">Delete</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Add Reward Modal (Overlay) -->
      <div *ngIf="showModal" class="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
        <div class="bg-white border border-brand-border w-full max-w-md rounded-2xl shadow-xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
          <div class="p-5 border-b border-brand-border flex justify-between items-center">
            <h3 class="text-lg font-bold">Record Reward / Cashback</h3>
            <button (click)="closeModal()" class="text-text-sub hover:text-brand-primary-dark focus:outline-none">
              ✕
            </button>
          </div>

          <form [formGroup]="rewardForm" (ngSubmit)="onSubmit()" class="p-6 space-y-4">
            <div>
              <label class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Description / Title</label>
              <input 
                type="text" 
                formControlName="title" 
                placeholder="e.g. 1% HDFC Grocery Cashback, Credit Card Milestone"
                class="w-full px-4 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-sm focus:outline-none focus:border-brand-primary"
              >
            </div>

            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Reward Type</label>
                <select 
                  formControlName="rewardType"
                  class="w-full px-3 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-xs focus:outline-none focus:border-brand-primary"
                >
                  <option value="CASHBACK_1_PERCENT">1% Card Cashback</option>
                  <option value="MILESTONE_BONUS">Milestone Bonus</option>
                  <option value="REFERRAL">Referral Bonus</option>
                  <option value="REWARD_POINTS">Points Conversion</option>
                </select>
              </div>

              <div>
                <label class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Cashback (₹)</label>
                <input 
                  type="number" 
                  step="0.01" 
                  formControlName="amount" 
                  placeholder="0.00"
                  class="w-full px-4 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-sm focus:outline-none focus:border-brand-primary"
                >
              </div>
            </div>

            <div>
              <label class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Status</label>
              <select 
                formControlName="status"
                class="w-full px-3 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-xs focus:outline-none focus:border-brand-primary"
              >
                <option value="EARNED">Earned / Credited</option>
                <option value="PENDING">Pending Settlement</option>
              </select>
            </div>

            <div class="flex justify-end gap-3 pt-4 border-t border-brand-border">
              <button 
                type="button" 
                (click)="closeModal()"
                class="px-4 py-2.5 border border-brand-border hover:bg-brand-bg text-text-sub text-xs font-bold rounded-xl focus:outline-none"
              >
                Cancel
              </button>
              <button 
                type="submit" 
                [disabled]="formSubmitting"
                class="px-5 py-2.5 bg-brand-primary hover:bg-brand-primary-dark text-white text-xs font-bold rounded-xl focus:outline-none shadow-sm hover:shadow"
              >
                Save Reward
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `
})
export class RewardsComponent implements OnInit {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private rewardService = inject(RewardService);

  rewards: any[] = [];
  loading = false;
  isDemoMode = true;
  showGuide = true;

  totalCashback = 3450;
  creditedCashback = 2800;
  pendingCashback = 650;
  totalPoints = 1250;

  showModal = false;
  formSubmitting = false;
  userId = '';

  liveRewards: any[] = [];
  liveTotalCashback = 0;
  liveCreditedCashback = 0;
  livePendingCashback = 0;

  readonly demoRewards = [
    {
      rewardId: 'rew-1',
      title: '1% Instant Cashback on Grocery Shopping',
      rewardType: 'CASHBACK_1_PERCENT',
      amount: 48.00,
      status: 'CREDITED',
      earnedDate: new Date(Date.now() - 86400000).toISOString()
    },
    {
      rewardId: 'rew-2',
      title: 'Amazon Electronics 5% Promotional Cashback',
      rewardType: 'MILESTONE_BONUS',
      amount: 325.00,
      status: 'CREDITED',
      earnedDate: new Date(Date.now() - 86400000 * 3).toISOString()
    },
    {
      rewardId: 'rew-3',
      title: 'ICICI Coral Card Monthly Spend Milestone Reward',
      rewardType: 'MILESTONE_BONUS',
      amount: 500.00,
      status: 'PENDING',
      earnedDate: new Date(Date.now() - 86400000 * 5).toISOString()
    },
    {
      rewardId: 'rew-4',
      title: 'BACHAT Referral Incentive Bonus',
      rewardType: 'REFERRAL',
      amount: 250.00,
      status: 'CREDITED',
      earnedDate: new Date(Date.now() - 86400000 * 10).toISOString()
    }
  ];

  rewardForm: FormGroup = this.fb.group({
    title: ['', [Validators.required]],
    rewardType: ['CASHBACK_1_PERCENT', [Validators.required]],
    amount: ['', [Validators.required, Validators.min(0.01)]],
    status: ['EARNED', [Validators.required]]
  });

  ngOnInit() {
    const session = this.authService.currentUser();
    this.userId = session ? session.userId : 'demo-user-id';

    this.applyDemoData();

    if (session) {
      this.loadRewards();
    }
  }

  toggleGuide() {
    this.showGuide = !this.showGuide;
  }

  setMode(demo: boolean) {
    this.isDemoMode = demo;
    if (demo) {
      this.applyDemoData();
    } else {
      this.applyLiveData();
    }
  }

  private applyDemoData() {
    this.rewards = [...this.demoRewards];
    this.totalCashback = 3450;
    this.creditedCashback = 2800;
    this.pendingCashback = 650;
    this.totalPoints = 1250;
    this.loading = false;
  }

  private applyLiveData() {
    this.rewards = [...this.liveRewards];
    this.totalCashback = this.liveTotalCashback;
    this.creditedCashback = this.liveCreditedCashback;
    this.pendingCashback = this.livePendingCashback;
    this.loading = false;
  }

  loadRewards() {
    this.rewardService.getRewards(this.userId).subscribe({
      next: (res: any) => {
        if (res && res.data) {
          this.liveRewards = res.data;
          this.liveTotalCashback = 0;
          this.liveCreditedCashback = 0;
          this.livePendingCashback = 0;
          this.liveRewards.forEach(r => {
            this.liveTotalCashback += r.amount || 0;
            if (r.status === 'CREDITED' || r.status === 'EARNED') {
              this.liveCreditedCashback += r.amount || 0;
            } else {
              this.livePendingCashback += r.amount || 0;
            }
          });
          if (!this.isDemoMode) {
            this.applyLiveData();
          }
        }
      },
      error: (err) => console.warn('Could not load live rewards', err)
    });
  }

  openAddModal() {
    this.rewardForm.reset({
      title: '',
      rewardType: 'CASHBACK_1_PERCENT',
      amount: '',
      status: 'EARNED'
    });
    this.showModal = true;
  }

  closeModal() {
    this.showModal = false;
  }

  onSubmit() {
    if (this.rewardForm.invalid) return;

    this.formSubmitting = true;
    const formVal = this.rewardForm.value;

    if (this.isDemoMode) {
      const newRew = {
        rewardId: 'rew-' + Date.now(),
        title: formVal.title,
        rewardType: formVal.rewardType,
        amount: parseFloat(formVal.amount),
        status: formVal.status,
        earnedDate: new Date().toISOString()
      };
      this.rewards.unshift(newRew);
      this.totalCashback += newRew.amount;
      this.formSubmitting = false;
      this.closeModal();
      return;
    }

    const payload = {
      ...formVal,
      userId: this.userId,
      earnedDate: new Date().toISOString()
    };

    this.rewardService.createReward(payload).subscribe({
      next: () => {
        this.formSubmitting = false;
        this.closeModal();
        this.loadRewards();
      },
      error: (err) => {
        this.formSubmitting = false;
        alert(err?.error?.message || 'Failed to record reward.');
      }
    });
  }

  deleteReward(id: string) {
    if (confirm('Are you sure you want to delete this reward record?')) {
      if (this.isDemoMode) {
        this.rewards = this.rewards.filter(r => r.rewardId !== id);
        return;
      }
      this.rewardService.deleteReward(id).subscribe({
        next: () => this.loadRewards(),
        error: (err) => alert(err?.error?.message || 'Failed to delete reward.')
      });
    }
  }
}
