import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { RewardService } from '../../core/services/reward.service';

@Component({
  selector: 'app-rewards',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div class="space-y-8 text-text-main animate-fade-in">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 class="text-3xl font-extrabold tracking-tight text-text-main">Rewards & Cashback</h1>
          <p class="text-text-sub text-sm mt-1">Track reward points and real cashbacks generated by your transactions.</p>
        </div>
        <button 
          (click)="openAddModal()" 
          class="px-5 py-3 bg-brand-primary hover:bg-brand-primary-dark text-white text-sm font-bold rounded-2xl shadow-sm hover:shadow transition-all duration-200 focus:outline-none flex items-center justify-center gap-2"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg>
          Record Reward
        </button>
      </div>

      <!-- Cashback Summary Cards -->
      <div *ngIf="!loading" class="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div class="bg-brand-primary-light border border-brand-primary p-5 rounded-2xl shadow-sm">
          <span class="text-[10px] font-bold text-brand-primary-dark uppercase tracking-wider">Total Cashback</span>
          <h3 class="text-2xl font-black text-brand-primary-dark mt-1">₹{{ totalCashback | number:'1.2-2' }}</h3>
        </div>
        <div class="bg-white border border-brand-border p-5 rounded-2xl shadow-sm">
          <span class="text-[10px] font-bold text-text-sub uppercase tracking-wider">Credited Cash</span>
          <h3 class="text-2xl font-black text-emerald-600 mt-1">₹{{ creditedCashback | number:'1.2-2' }}</h3>
        </div>
        <div class="bg-white border border-brand-border p-5 rounded-2xl shadow-sm">
          <span class="text-[10px] font-bold text-text-sub uppercase tracking-wider">Pending Release</span>
          <h3 class="text-2xl font-black text-orange-500 mt-1">₹{{ pendingCashback | number:'1.2-2' }}</h3>
        </div>
        <div class="bg-white border border-brand-border p-5 rounded-2xl shadow-sm">
          <span class="text-[10px] font-bold text-text-sub uppercase tracking-wider">Redeemed Points</span>
          <h3 class="text-2xl font-black text-purple-600 mt-1">{{ totalPoints | number:'1.0-0' }} pts</h3>
        </div>
      </div>

      <!-- State: Loading -->
      <div *ngIf="loading" class="p-12 text-center text-xs text-text-sub">
        Loading rewards details...
      </div>

      <!-- Empty state -->
      <div *ngIf="!loading && rewards.length === 0" class="bg-white border border-brand-border p-12 rounded-2xl text-center shadow-sm space-y-3">
        <p class="text-sm text-text-sub">No reward items recorded yet.</p>
        <button (click)="openAddModal()" class="text-xs text-brand-primary font-bold underline">Add a reward item</button>
      </div>

      <!-- History Table -->
      <div *ngIf="!loading && rewards.length > 0" class="bg-white border border-brand-border rounded-2xl shadow-sm overflow-hidden">
        <div class="p-5 border-b border-brand-border">
          <h3 class="text-base font-bold">Rewards & Cashback History</h3>
          <p class="text-xs text-text-sub">Log of all reward updates</p>
        </div>

        <div class="overflow-x-auto">
          <table class="w-full text-left border-collapse">
            <thead>
              <tr class="bg-brand-bg border-b border-brand-border text-[10px] font-bold text-text-sub uppercase tracking-wider">
                <th class="p-4">Description</th>
                <th class="p-4">Points</th>
                <th class="p-4">Cashback (₹)</th>
                <th class="p-4">Expiry Date</th>
                <th class="p-4">Status</th>
                <th class="p-4 text-center">Actions</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-brand-border text-sm">
              <tr *ngFor="let r of rewards" class="hover:bg-brand-bg transition-colors duration-150">
                <td class="p-4 font-bold text-text-main">{{ r.description || 'Reward Reward' }}</td>
                <td class="p-4 text-text-sub font-semibold">{{ r.rewardPoints }} pts</td>
                <td class="p-4 text-emerald-600 font-extrabold">₹{{ r.cashbackAmount | number:'1.2-2' }}</td>
                <td class="p-4 text-text-sub text-xs">{{ r.expiryDate | date:'MMM d, yyyy' }}</td>
                <td class="p-4">
                  <span 
                    [class.bg-emerald-50]="r.status === 'CREDITED'" [class.text-emerald-700]="r.status === 'CREDITED'"
                    [class.bg-orange-50]="r.status === 'PENDING'" [class.text-orange-700]="r.status === 'PENDING'"
                    [class.bg-purple-50]="r.status === 'REDEEMED'" [class.text-purple-700]="r.status === 'REDEEMED'"
                    class="px-2.5 py-0.5 border rounded-lg text-xs font-bold"
                  >
                    {{ r.status }}
                  </span>
                </td>
                <td class="p-4 text-center space-x-2">
                  <button (click)="openEditModal(r)" class="text-xs text-brand-primary font-bold">Edit</button>
                  <button (click)="deleteReward(r.rewardId)" class="text-xs text-red-500 font-bold">Delete</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Add/Edit Modal (Overlay) -->
      <div *ngIf="showModal" class="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
        <div class="bg-white border border-brand-border w-full max-w-md rounded-2xl shadow-xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
          <div class="p-5 border-b border-brand-border flex justify-between items-center">
            <h3 class="text-lg font-bold">{{ editingRewardId ? 'Edit Reward Log' : 'Record Reward' }}</h3>
            <button (click)="closeModal()" class="text-text-sub hover:text-brand-primary-dark focus:outline-none">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <form [formGroup]="rewardForm" (ngSubmit)="onSubmit()" class="p-6 space-y-4">
            <!-- Description -->
            <div>
              <label for="description" class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Source / Description</label>
              <input 
                id="description" 
                type="text" 
                formControlName="description" 
                placeholder="e.g. Amazon Pay Cashback, Credit Card Points"
                class="w-full px-4 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-sm focus:outline-none focus:border-brand-primary"
              >
              <p *ngIf="isFieldInvalid('description')" class="text-xs text-red-500 mt-1">Description is required</p>
            </div>

            <div class="grid grid-cols-2 gap-4">
              <!-- Reward Points -->
              <div>
                <label for="rewardPoints" class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Points</label>
                <input 
                  id="rewardPoints" 
                  type="number" 
                  formControlName="rewardPoints" 
                  placeholder="0"
                  class="w-full px-4 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-sm focus:outline-none focus:border-brand-primary"
                >
              </div>

              <!-- Cashback Amount -->
              <div>
                <label for="cashbackAmount" class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Cashback (₹)</label>
                <input 
                  id="cashbackAmount" 
                  type="number" 
                  formControlName="cashbackAmount" 
                  placeholder="0.00"
                  class="w-full px-4 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-sm focus:outline-none focus:border-brand-primary"
                >
              </div>
            </div>

            <div class="grid grid-cols-2 gap-4">
              <!-- Status -->
              <div>
                <label for="status" class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Status</label>
                <select 
                  id="status"
                  formControlName="status"
                  class="w-full px-3 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-sm focus:outline-none focus:border-brand-primary"
                >
                  <option value="PENDING">Pending Release</option>
                  <option value="CREDITED">Credited to Balance</option>
                  <option value="REDEEMED">Redeemed</option>
                </select>
              </div>

              <!-- Expiry Date -->
              <div>
                <label for="expiryDate" class="block text-xs font-bold text-text-sub uppercase tracking-wider mb-1">Expiry Date</label>
                <input 
                  id="expiryDate" 
                  type="date" 
                  formControlName="expiryDate"
                  class="w-full px-4 py-2.5 border border-brand-border bg-brand-bg rounded-xl text-xs focus:outline-none focus:border-brand-primary"
                >
              </div>
            </div>

            <div class="flex justify-end gap-3 pt-4 border-t border-brand-border">
              <button 
                type="button" 
                (click)="closeModal()" 
                class="px-4 py-2.5 border border-brand-border rounded-xl text-xs font-bold text-text-sub hover:bg-brand-bg focus:outline-none"
              >
                Cancel
              </button>
              <button 
                type="submit" 
                [disabled]="formSubmitting"
                class="px-5 py-2.5 bg-brand-primary hover:bg-brand-primary-dark text-white text-xs font-bold rounded-xl focus:outline-none shadow-sm hover:shadow"
              >
                {{ formSubmitting ? 'Saving...' : 'Save Reward' }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `
})
export class RewardsComponent implements OnInit {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private rewardService = inject(RewardService);

  rewards: any[] = [];
  loading = true;
  showModal = false;
  editingRewardId: string | null = null;
  formSubmitting = false;
  userId = '';

  // Metrics
  totalCashback = 0;
  creditedCashback = 0;
  pendingCashback = 0;
  totalPoints = 0;

  rewardForm: FormGroup = this.fb.group({
    description: ['', [Validators.required]],
    rewardPoints: [0, [Validators.required, Validators.min(0)]],
    cashbackAmount: [0, [Validators.required, Validators.min(0)]],
    status: ['CREDITED', [Validators.required]],
    expiryDate: ['', [Validators.required]]
  });

  ngOnInit() {
    const session = this.authService.currentUser();
    if (session) {
      this.userId = session.userId;
      this.loadRewards();
    }
  }

  loadRewards() {
    this.loading = true;
    this.totalCashback = 0;
    this.creditedCashback = 0;
    this.pendingCashback = 0;
    this.totalPoints = 0;

    this.rewardService.getRewards(this.userId).subscribe({
      next: (res: any) => {
        if (res && res.data) {
          this.rewards = res.data;
          this.rewards.forEach(r => {
            this.totalCashback += r.cashbackAmount || 0;
            this.totalPoints += r.rewardPoints || 0;
            if (r.status === 'CREDITED') this.creditedCashback += r.cashbackAmount || 0;
            if (r.status === 'PENDING') this.pendingCashback += r.cashbackAmount || 0;
          });
        }
        this.loading = false;
      },
      error: (err) => {
        console.error('Error loading rewards', err);
        this.loading = false;
      }
    });
  }

  isFieldInvalid(field: string): boolean {
    const control = this.rewardForm.get(field);
    return !!(control && control.invalid && (control.dirty || control.touched));
  }

  openAddModal() {
    this.editingRewardId = null;
    
    // Default expiry 1 year out
    const nextYear = new Date();
    nextYear.setFullYear(nextYear.getFullYear() + 1);
    const dateStr = nextYear.toISOString().substring(0, 10);

    this.rewardForm.reset({
      description: '',
      rewardPoints: 0,
      cashbackAmount: '',
      status: 'CREDITED',
      expiryDate: dateStr
    });
    this.showModal = true;
  }

  openEditModal(reward: any) {
    this.editingRewardId = reward.rewardId;
    this.rewardForm.reset({
      description: reward.description,
      rewardPoints: reward.rewardPoints,
      cashbackAmount: reward.cashbackAmount,
      status: reward.status,
      expiryDate: reward.expiryDate ? reward.expiryDate.substring(0, 10) : ''
    });
    this.showModal = true;
  }

  closeModal() {
    this.showModal = false;
  }

  onSubmit() {
    if (this.rewardForm.invalid) {
      this.rewardForm.markAllAsTouched();
      return;
    }

    this.formSubmitting = true;
    const payload = {
      ...this.rewardForm.value,
      userId: this.userId
    };

    if (this.editingRewardId) {
      this.rewardService.updateReward(this.editingRewardId, payload).subscribe({
        next: () => {
          this.formSubmitting = false;
          this.closeModal();
          this.loadRewards();
        },
        error: (err) => {
          this.formSubmitting = false;
          alert(err?.error?.message || 'Failed to update reward record.');
        }
      });
    } else {
      this.rewardService.createReward(payload).subscribe({
        next: () => {
          this.formSubmitting = false;
          this.closeModal();
          this.loadRewards();
        },
        error: (err) => {
          this.formSubmitting = false;
          alert(err?.error?.message || 'Failed to record reward.');
        }
      });
    }
  }

  deleteReward(id: string) {
    if (confirm('Are you sure you want to delete this reward log?')) {
      this.rewardService.deleteReward(id).subscribe({
        next: () => {
          this.loadRewards();
        },
        error: (err) => {
          alert(err?.error?.message || 'Failed to delete reward.');
        }
      });
    }
  }
}
